/**
 * Downloads the latin subsets of the report typefaces and writes them into
 * src/fonts.ts as base64 @font-face rules.
 *
 * The report has to keep working with no network, so a Google Fonts <link>
 * is not an option -- it would silently fall back to system faces on a phone
 * with no signal, which is exactly when the report gets read. Inlining costs
 * about 100KB once and keeps the page genuinely self-contained.
 *
 * Run only when changing typefaces:  node tools/build-fonts.mjs
 */
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "fonts.ts");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

const FAMILIES = [
  { name: "Archivo", spec: "Archivo:wght@500;600;700" },
  { name: "IBM Plex Mono", spec: "IBM+Plex+Mono:wght@400;600" },
];

/** Google serves per-subset @font-face blocks; only latin is needed here. */
function latinBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g;
  let m;
  while ((m = re.exec(css)) !== null) {
    if (m[1] === "latin") blocks.push(m[2]);
  }
  return blocks;
}

const chunks = [];

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.spec}&display=swap`;
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.text());
  const blocks = latinBlocks(css);
  if (blocks.length === 0) throw new Error(`No latin subset found for ${fam.name}`);

  for (const block of blocks) {
    const srcUrl = block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+\.woff2)\)/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? "400";
    const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? "normal";
    if (!srcUrl) continue;

    const buf = Buffer.from(
      await fetch(srcUrl, { headers: { "User-Agent": UA } }).then((r) => r.arrayBuffer()),
    );
    const b64 = buf.toString("base64");
    chunks.push(
      `@font-face{font-family:'${fam.name}';font-style:${style};font-weight:${weight};font-display:swap;` +
        `src:url(data:font/woff2;base64,${b64}) format('woff2')}`,
    );
    console.log(`${fam.name} ${weight} ${style}  ${(buf.length / 1024).toFixed(1)} KB`);
  }
}

const css = chunks.join("\n");
const out =
  `/**\n * Inlined latin subsets of the report typefaces, base64 woff2.\n *\n` +
  ` * Generated by tools/build-fonts.mjs -- do not edit by hand.\n` +
  ` * Inlined rather than linked so the report keeps its typography with no\n` +
  ` * network, which is the state it is most often read in.\n */\n` +
  `export const FONT_CSS = ${JSON.stringify(css)};\n`;

await writeFile(OUT, out, "utf8");
console.log(`\n${OUT}  (${(Buffer.byteLength(out, "utf8") / 1024).toFixed(0)} KB)`);
