import { readFile } from "node:fs/promises";
import { FONT_CSS } from "./fonts.ts";
import type { VolEmbed, Calibration, Events } from "./volindex.ts";
import type { RuleBook } from "./types.ts";

/**
 * Real volatility for the option prices: index levels per replayed day, and
 * the per-ticker calibrations. `rulebook` is Alex's Rules from rules.json,
 * shown in the Rules tab beside the numbers the simulator enforces.
 */
export interface PracticeVol { embed: VolEmbed; calibrations: Calibration[]; events?: Events; rulebook?: RuleBook | null }
import type { ReplaySession, ExtBar } from "./replay.ts";

/**
 * The practice terminal, re-skinned to match the report.
 *
 * The app's own markup and script are kept verbatim -- every class name in it
 * is load-bearing, since the script builds panes by writing those classes -- so
 * this replaces the stylesheet and wraps the result in the report's chrome
 * rather than rewriting the app.
 *
 * The prices in here are generated by a seeded random walk. That is the whole
 * point of a practice tool, but it sits one click from a report where every
 * number is measured from real bars, so the page says which it is in a place
 * you cannot scroll past.
 */

const SKIN = `
${FONT_CSS}
:root{
  /* The report's tokens, mapped onto the names the app already uses. */
  --bg:#080b11; --panel:#121826; --p2:#0d1220; --line:#1d2637; --line2:#2b3547;
  --text:#e9edf5; --dim:#8994a6; --dim2:#67717f;
  --up:#2dd4a7; --dn:#f4525f; --fib:#f5a524; --acc:#7b6cf6;
  color-scheme:dark;
  --mono:'IBM Plex Mono',ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  --sans:'Archivo',-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
html,body{margin:0;background:var(--bg);color:var(--text);font-family:var(--sans);font-size:14px;overscroll-behavior:none}
button,input,select{font-family:var(--sans);color:var(--text);font-size:13.5px}
button{cursor:pointer;background:var(--p2);border:1px solid var(--line2);border-radius:8px;padding:0 12px;min-height:38px;font-weight:600}
button:active:not(:disabled){transform:scale(.97)}
button:disabled{opacity:.3}
button:focus-visible,select:focus-visible,input:focus-visible{outline:2px solid var(--acc);outline-offset:1px}
input,select{background:var(--p2);border:1px solid var(--line2);border-radius:8px;padding:9px 10px;width:100%;
  font-family:var(--mono);font-size:14px}
.n,.px,.chg,.clk,.ohlc,.seed{font-family:var(--mono);font-variant-numeric:tabular-nums}
.up,.u{color:var(--up)} .dn,.d{color:var(--dn)}

/* ---- masthead ---------------------------------------------------- */
.mp-head{border-bottom:1px solid var(--line);padding:20px 0 0;position:relative;overflow:hidden}
.mp-head::before{content:"";position:absolute;inset:-60% -20% auto -20%;height:220%;
  background:radial-gradient(60% 55% at 18% 40%,rgba(123,108,246,.16),transparent 70%);pointer-events:none}
.mp-wrap{max-width:1300px;margin:0 auto;padding:0 14px;position:relative}
.mp-brand{display:flex;align-items:flex-end;gap:16px;flex-wrap:wrap}
.mp-brand h1{margin:0;font-size:27px;line-height:1;letter-spacing:-1px;font-weight:700}
.mp-brand p{margin:6px 0 0;color:var(--dim);font-size:12.5px}
.mp-back{margin-left:auto;display:inline-flex;align-items:center;gap:7px;text-decoration:none;
  border:1px solid var(--line2);border-radius:8px;padding:9px 14px;color:var(--dim);font-weight:650;font-size:13px}
.mp-back:hover{color:var(--text);border-color:var(--acc);background:rgba(123,108,246,.1)}
.sim{display:flex;align-items:flex-start;gap:10px;margin:16px 0 0;padding:11px 14px;border-radius:9px;
  border:1px solid rgba(245,165,36,.4);background:rgba(245,165,36,.08);color:var(--fib);font-size:12.5px;line-height:1.5}
.sim b{display:block;font-size:11px;text-transform:uppercase;letter-spacing:1.2px;margin-bottom:3px}
.sim.real{border-color:rgba(45,212,167,.38);background:rgba(45,212,167,.07);color:var(--up)}
.sim span{color:var(--dim)}

/* ---- app chrome -------------------------------------------------- */
.top{position:sticky;top:0;z-index:20;background:rgba(8,11,17,.94);backdrop-filter:blur(10px);
  border-bottom:1px solid var(--line);padding:10px 14px 9px}
.row1{display:flex;align-items:center;gap:11px;max-width:1300px;margin:0 auto}
/* The ticker used to be bare text with a faint caret -- it read as a heading,
   so nobody found out it could be changed. It is a bordered control now. */
.tksel{background-color:var(--p2);border:1px solid var(--line2);border-radius:9px;font-family:var(--sans);font-size:19px;
  font-weight:700;letter-spacing:-.3px;padding:3px 28px 3px 11px;min-height:0;width:auto;cursor:pointer;
  -webkit-appearance:none;appearance:none;
  background-image:linear-gradient(45deg,transparent 50%,var(--dim) 50%),linear-gradient(135deg,var(--dim) 50%,transparent 50%);
  background-position:calc(100% - 15px) 50%,calc(100% - 10px) 50%;background-size:5px 5px;background-repeat:no-repeat}
.tksel:hover{border-color:var(--acc)}
.px{font-size:20px;font-weight:600;letter-spacing:-.4px}
.chg{font-size:12px;padding:2px 8px;border-radius:5px;font-weight:600}
.chg.u{color:var(--up);background:rgba(45,212,167,.14)}
.chg.d{color:var(--dn);background:rgba(244,82,95,.14)}
.clk{margin-left:auto;font-size:12px;color:var(--dim);text-align:right;line-height:1.3;white-space:nowrap}
.clk #clk{color:var(--text);font-weight:600;font-size:13px}
.clkx{font-size:10.5px}
.ohlc{font-size:12.5px;color:#a3adbb;margin:8px auto 0;max-width:1300px;height:17px;white-space:nowrap;overflow:hidden}
.ohlc b{color:var(--text);font-weight:600}

/* Restart / new day / which day: in the header, where they can be found. */
.sessrow{display:flex;gap:7px;align-items:center;max-width:1300px;margin:9px auto 0}
.ssel{flex:0 1 240px;min-width:0;width:auto;min-height:34px;padding:0 28px 0 11px;font-family:var(--mono);font-size:12.5px;
  border-radius:8px;background-color:var(--p2);border:1px solid var(--line2);color:var(--text);cursor:pointer;
  -webkit-appearance:none;appearance:none;
  background-image:linear-gradient(45deg,transparent 50%,var(--dim) 50%),linear-gradient(135deg,var(--dim) 50%,transparent 50%);
  background-position:calc(100% - 15px) 50%,calc(100% - 10px) 50%;background-size:5px 5px;background-repeat:no-repeat}
.ssel:disabled{opacity:.5;cursor:default}
.sbtn{flex:0 0 auto;min-height:34px;padding:0 13px;font-size:12.5px;white-space:nowrap}
.sbtn.sprim{background:rgba(123,108,246,.16);border-color:var(--acc);color:var(--text)}

.tfbar{display:flex;gap:5px;overflow-x:auto;padding:9px 14px 8px;scrollbar-width:none;
  border-bottom:1px solid var(--line);background:var(--bg);max-width:1300px;margin:0 auto}
.tfbar::-webkit-scrollbar{display:none}
.tf{flex:0 0 auto;min-height:32px;padding:0 13px;border-radius:8px;font-family:var(--mono);font-size:12.5px;
  background:transparent;border:1px solid var(--line2);color:var(--dim);font-weight:500}
.tf.on{background:rgba(123,108,246,.16);border-color:var(--acc);color:var(--text);font-weight:600}

.chartbox{position:relative;background:#0b1017}
canvas{display:block;width:100%;touch-action:none}
/* The indicator chips are a strip of their own above the chart, on every
   screen: floated over the candles they covered the first hour of the day,
   and at ten-pixel mono they were the hardest thing on the page to read. */
.ov{display:flex;gap:6px;flex-wrap:nowrap;overflow-x:auto;padding:8px 12px;background:var(--panel);
  border-top:1px solid var(--line);scrollbar-width:none;-webkit-overflow-scrolling:touch}
.ov::-webkit-scrollbar{display:none}
.badge{flex:0 0 auto;font-family:var(--sans);font-size:12.5px;min-height:32px;padding:0 12px;border-radius:8px;font-weight:600;
  background:transparent;border:1px solid var(--line2);color:var(--dim);display:grid;place-items:center;letter-spacing:.1px}
.badge:hover{border-color:var(--acc);color:var(--text)}
.badge.on{color:var(--text);border-color:var(--acc);background:rgba(123,108,246,.18)}
.ctsel{flex:0 0 auto;font-family:var(--sans);font-size:12.5px;font-weight:600;min-height:32px;padding:0 24px 0 11px;width:auto;border-radius:8px;
  background-color:var(--p2);border:1px solid var(--line2);color:var(--text);cursor:pointer;
  -webkit-appearance:none;appearance:none;
  background-image:linear-gradient(45deg,transparent 50%,var(--dim) 50%),linear-gradient(135deg,var(--dim) 50%,transparent 50%);
  background-position:calc(100% - 13px) 50%,calc(100% - 8px) 50%;background-size:5px 5px;background-repeat:no-repeat}
.fitbtn{position:absolute;left:10px;top:10px;font-family:var(--sans);font-size:11.5px;font-weight:600;padding:5px 10px;
  min-height:0;background:rgba(123,108,246,.2);border:1px solid var(--acc);color:var(--text);display:none;border-radius:7px}
.fitbtn.show{display:block}
/* A strip that overflows gets arrows at the edges that scroll it -- the tabs
   on a phone, the chips, the timeframes -- since a hidden scrollbar is no
   sign that Session and Rules exist past the edge. */
.strip{position:relative;min-width:0}
.strip .sa{position:absolute;top:0;bottom:0;width:34px;min-height:0;padding:0;border:none;border-radius:0;z-index:3;
  color:var(--acc);font-size:20px;font-weight:700;display:none;cursor:pointer;line-height:1}
.strip .sa.l{left:0;background:linear-gradient(90deg,var(--sbg) 55%,transparent)}
.strip .sa.r{right:0;background:linear-gradient(270deg,var(--sbg) 55%,transparent)}
.strip .sa.show{display:block}
.strip .sa:active{transform:none}

.rail{display:flex;gap:6px;overflow-x:auto;padding:9px 12px;background:var(--panel);
  border-top:1px solid var(--line);border-bottom:1px solid var(--line);scrollbar-width:none}
.rail::-webkit-scrollbar{display:none}
.tool{flex:0 0 auto;width:42px;height:38px;display:grid;place-items:center;padding:0;background:transparent;border:1px solid var(--line2)}
.tool.on{background:rgba(123,108,246,.18);border-color:var(--acc)}
.tool.on svg{stroke:var(--acc)}
.tool svg{width:18px;height:18px;fill:none;stroke:var(--dim);stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}
.rail .lbl{flex:0 0 auto;align-self:center;font-size:10px;color:var(--dim2);text-transform:uppercase;letter-spacing:1.1px;font-weight:600;padding-right:2px}

/* Two rows, each with its own track sizes. One grid cannot do this: the side
   buttons would inherit the transport columns and come out uneven -- which is
   how Buy put ended up half the width of Buy call. */
.actions{position:sticky;bottom:0;z-index:18;display:flex;flex-direction:column;gap:7px;
  padding:10px 12px;background:rgba(8,11,17,.96);backdrop-filter:blur(10px);border-top:1px solid var(--line)}
.trow{display:grid;grid-template-columns:46px 1fr 46px 76px;gap:7px}
.srow{display:grid;grid-template-columns:1fr 1fr;gap:7px}
.actions button{min-height:46px;font-weight:650;font-size:13.5px;padding:0 4px;white-space:nowrap}
.actions select{min-height:46px;padding:0 4px;font-size:12.5px;text-align:center}
.actions #back,.actions #auto{font-size:15px;padding:0}
.bnext{background:var(--acc);border-color:var(--acc);color:#fff}
.blong{border-color:rgba(45,212,167,.55);color:var(--up);background:rgba(45,212,167,.1)}
.bshort{border-color:rgba(244,82,95,.5);color:var(--dn);background:rgba(244,82,95,.1)}

/* ---- panes ------------------------------------------------------- */
.tabs{display:flex;gap:4px;overflow-x:auto;padding:12px 0 0;scrollbar-width:none;scroll-behavior:smooth}
.tabs::-webkit-scrollbar{display:none}
.tab{flex:0 0 auto;min-height:34px;padding:0 13px;font-size:12.5px;background:transparent;border:1px solid transparent;
  color:var(--dim);border-radius:8px 8px 0 0;font-weight:600}
.tab.on{background:var(--panel);border-color:var(--line);border-bottom-color:var(--panel);color:var(--text)}
.pane{background:var(--panel);border:1px solid var(--line);border-radius:0 10px 10px 10px;margin:0 0 14px;padding:14px;min-height:190px}
h3{font-size:10.5px;color:var(--dim2);font-weight:650;margin:0 0 10px;text-transform:uppercase;letter-spacing:1.2px}
h3.sp{margin-top:18px}
.empty{color:var(--dim);font-size:13px;line-height:1.55}

.seg{display:flex;border:1px solid var(--line2);border-radius:9px;overflow:hidden;margin-bottom:12px}
.seg button{flex:1;border:none;border-radius:0;background:transparent;min-height:40px;color:var(--dim)}
.seg button.on{background:rgba(123,108,246,.2);color:var(--text);font-weight:700;box-shadow:inset 0 -2px 0 var(--acc)}
.chips{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}
.chips button{min-height:34px;font-size:11.5px;font-family:var(--mono);padding:0 10px;font-weight:500}
.chips button.on{border-color:var(--acc);color:var(--text);background:rgba(123,108,246,.14)}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:9px}
.grid2 label{font-size:10.5px;color:var(--dim2);text-transform:uppercase;letter-spacing:.9px;font-weight:600}
.grid2 label span{display:block;margin-bottom:5px}
.quote{background:var(--p2);border:1px solid var(--line2);border-radius:9px;padding:11px;margin-top:11px}
.quote .big{font-family:var(--mono);font-size:18px;font-weight:600;letter-spacing:-.3px}
.greeks{display:flex;gap:12px;flex-wrap:wrap;font-family:var(--mono);font-size:11px;color:var(--dim);margin-top:8px}
.greeks b{color:var(--text);font-weight:600}
.kv{display:flex;justify-content:space-between;font-family:var(--mono);font-size:13px;padding:6px 0;border-bottom:1px solid var(--line)}
.kv:last-child{border-bottom:none}
.kv .k{color:var(--dim)}
.mgmt{display:grid;grid-template-columns:1fr 1fr 1fr;gap:7px;margin-top:11px}
.mgmt button{min-height:40px;font-size:12.5px}
.fibrow{display:flex;justify-content:space-between;font-family:var(--mono);font-size:12.5px;padding:7px 9px;border-radius:6px}
.fibrow+.fibrow{margin-top:1px}
.fibrow .k{color:var(--dim)}
.fibrow.ext .k{color:var(--fib)}
.fibrow.edge{background:rgba(123,108,246,.12)}
.fibrow.edge .k{color:var(--acc)}
.fibrow.near{outline:1px solid var(--line2)}
.fibrow small{color:var(--dim2);font-size:10.5px;margin-left:5px}
.tape div{font-family:var(--mono);font-size:12px;color:var(--dim);padding:3px 0;line-height:1.45}
.tape .hl{color:var(--text)} .tape .g{color:var(--up)} .tape .r{color:var(--dn)} .tape .y{color:var(--fib)}
.scroll{max-height:270px;overflow-y:auto;-webkit-overflow-scrolling:touch}
.scroll::-webkit-scrollbar{width:8px} .scroll::-webkit-scrollbar-thumb{background:var(--line2);border-radius:4px}
table{width:100%;border-collapse:collapse;font-family:var(--mono);font-size:11.5px}
th{text-align:left;color:var(--dim2);font-weight:650;padding:6px 4px;border-bottom:1px solid var(--line2);
  text-transform:uppercase;letter-spacing:.7px;font-size:9.5px}
td{padding:7px 4px;border-bottom:1px solid var(--line)}
tr.atm td{background:rgba(123,108,246,.1)}
tr.pick td{outline:1px solid var(--acc)}
.chain td{cursor:pointer}
.stats{display:flex;gap:14px;flex-wrap:wrap;font-family:var(--mono);font-size:13px;margin-bottom:12px}
.stats span{color:var(--dim)}
.gr{display:flex;gap:9px;padding:10px 0;border-bottom:1px solid var(--line)}
.gr:last-child{border-bottom:none}
.gr .m{font-family:var(--mono);font-size:13.5px;line-height:1.3}
.gr .m.ok{color:var(--up)} .gr .m.bad{color:var(--dn)} .gr .m.mid{color:var(--fib)} .gr .m.h{color:var(--acc)}
.gr .b{font-size:13px;line-height:1.55}
.setup{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:12px}
.setup select{width:auto;flex:1;min-width:130px}
.seed{font-size:12px;color:var(--acc);background:var(--p2);border:1px solid var(--line2);border-radius:7px;padding:9px 11px}
footer{color:var(--dim2);font-size:11px;text-align:center;padding:0 20px 28px;line-height:1.6;max-width:640px;margin:0 auto}

.wrap{max-width:1300px;margin:0 auto;padding:0 14px 20px}
.left{min-width:0}
/* ---- draw rail: every tool says what it is ---- */
.tool{width:54px;height:50px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px}
.tool small{font-size:10px;line-height:1;color:var(--dim);font-weight:600;letter-spacing:.1px}
.tool.on small{color:var(--text)}
.tool:hover{border-color:var(--acc)}

/* ---- a note over the chart ---- */
.hint{position:absolute;left:50%;top:40px;transform:translate(-50%,-4px);max-width:calc(100% - 110px);z-index:6;
  background:rgba(13,18,32,.96);border:1px solid var(--acc);color:var(--text);font-size:12.5px;line-height:1.4;
  padding:7px 12px;border-radius:9px;text-align:center;opacity:0;transition:opacity .22s,transform .22s;pointer-events:none;
  box-shadow:0 6px 24px rgba(0,0,0,.45)}
.hint.show{opacity:1;transform:translate(-50%,0)}
.hint[hidden]{display:none}

/* ---- guide ---- */
.sbtn.sq{width:34px;padding:0;font-size:15px;font-weight:700}
.mp-guide{margin-left:auto;display:inline-flex;align-items:center;gap:7px;border:1px solid var(--acc);border-radius:8px;
  padding:9px 14px;background:rgba(123,108,246,.14);color:var(--text);font-weight:650;font-size:13px;min-height:0}
.mp-guide + .mp-back{margin-left:0}
.tour{position:fixed;inset:0;z-index:100}
.tour[hidden]{display:none}
.tour.center{background:rgba(3,5,10,.72)}
.tour-spot{position:fixed;border-radius:10px;border:2px solid var(--acc);box-shadow:0 0 0 9999px rgba(3,5,10,.72);
  pointer-events:none}
.tour-card{position:fixed;background:var(--panel);border:1px solid var(--line2);border-radius:12px;padding:15px 16px 13px;
  box-shadow:0 18px 50px rgba(0,0,0,.6)}
.tour-step{font-family:var(--mono);font-size:11px;color:var(--acc);font-weight:600;letter-spacing:.4px}
.tour-card h4{margin:6px 0;font-size:16px;letter-spacing:-.2px}
.tour-card p{margin:0;color:#c3cad6;font-size:13.5px;line-height:1.55}
.tour-nav{display:flex;gap:8px;align-items:center;margin-top:14px}
.tour-nav button{min-height:36px;padding:0 14px;font-size:13px}
.tour-skip{margin-right:auto;background:transparent;border-color:transparent;color:var(--dim);padding-left:0}
.tour-next{background:var(--acc);border-color:var(--acc);color:#fff}

/* ---- ticket ---- */
h3 i{font-style:normal;text-transform:none;letter-spacing:0;color:var(--dim);font-weight:500;margin-left:4px}
.seg.exp button{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;min-height:50px}
.seg.exp b{font-family:var(--mono);font-size:13px}
.seg.exp small{font-size:10.5px;color:var(--dim);font-weight:500}
.seg.exp button.on small{color:var(--text)}
.stepper{display:grid;grid-template-columns:44px 1fr 44px;gap:6px}
.stepper button{min-height:42px;font-size:19px;padding:0;font-weight:500;line-height:1}
.stepper select,.stepper input{min-height:42px;text-align:center;text-align-last:center;font-family:var(--mono);font-size:14px}
.pair{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}
.oc{border:1px solid var(--line2);border-radius:10px;padding:10px 11px 9px;background:var(--p2);min-width:0}
.oc.call{border-color:rgba(45,212,167,.38);background:linear-gradient(180deg,rgba(45,212,167,.08),rgba(45,212,167,0) 55%),var(--p2)}
.oc.put{border-color:rgba(244,82,95,.38);background:linear-gradient(180deg,rgba(244,82,95,.08),rgba(244,82,95,0) 55%),var(--p2)}
.oc .hd{display:flex;justify-content:space-between;align-items:baseline;gap:6px;font-size:11.5px;font-weight:700;letter-spacing:.8px;text-transform:uppercase}
.oc.call .hd{color:var(--up)}
.oc.put .hd{color:var(--dn)}
.oc .hd span{color:var(--dim);font-weight:500;letter-spacing:0;text-transform:none;font-size:11px;white-space:nowrap}
.oc .ask{font-family:var(--mono);font-size:22px;font-weight:600;margin:6px 0 3px;letter-spacing:-.5px}
.oc .ask small{font-family:var(--sans);font-size:11px;color:var(--dim);font-weight:500;letter-spacing:0;margin-left:5px}
.oc .ln{font-family:var(--mono);font-size:11.5px;color:var(--dim);line-height:1.65;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.oc .ln b{color:var(--text);font-weight:600}
.oc .cost{margin-top:8px;padding-top:8px;border-top:1px solid var(--line);font-size:11.5px;color:var(--dim)}
.oc .cost b{display:block;margin-top:2px;color:var(--text);font-family:var(--mono);font-size:14px;font-weight:600}
.meta{font-size:12px;color:var(--dim);margin-top:9px;line-height:1.55}
.meta b{color:var(--text);font-weight:600}
.meta.tight{margin-top:-3px}
.stepline{display:grid;gap:6px}
.stepline label{font-size:10.5px;color:var(--dim2);text-transform:uppercase;letter-spacing:.9px;font-weight:600}
.plan{background:var(--p2);border:1px solid var(--line2);border-radius:9px;padding:10px 12px;margin-top:10px}
.plan .r{display:flex;justify-content:space-between;align-items:baseline;font-size:12.5px;padding:3px 0}
.plan .r span{color:var(--dim)}
.plan .r b{font-family:var(--mono);font-size:13.5px;font-weight:600}
.plan .note{margin:6px 0 0;font-size:11.5px;color:var(--dim);line-height:1.5}
.plan .r + .note{border-top:1px solid var(--line);padding-top:7px}
.plan .note:first-child{margin-top:0}
.plan .note.warn{color:var(--fib)}
.chk{display:flex;gap:9px;align-items:center;margin-top:12px;font-size:12.5px;color:var(--dim);cursor:pointer}
.chk input{width:auto;min-height:0;accent-color:var(--acc)}
.posline{font-family:var(--mono);font-size:14.5px;font-weight:600;margin:0 0 6px}
/* ---- the side cards are the buy buttons ---- */
button.oc{display:block;width:100%;text-align:left;font-weight:400;min-height:0;color:var(--text);cursor:pointer;
  transition:border-color .15s,box-shadow .15s,transform .08s}
button.oc > span{display:block}
button.oc > .hd{display:flex}
.oc.call:hover:not(:disabled){border-color:var(--up);box-shadow:0 0 0 1px var(--up)}
.oc.put:hover:not(:disabled){border-color:var(--dn);box-shadow:0 0 0 1px var(--dn)}
.oc.call:focus-visible{outline:2px solid var(--up);outline-offset:2px}
.oc.put:focus-visible{outline:2px solid var(--dn);outline-offset:2px}
button.oc:disabled{opacity:.5;cursor:not-allowed}
.oc .go{margin-top:9px;padding:8px 10px 9px;border-radius:8px;font-size:12px;font-weight:700;line-height:1.3}
.oc .go b{display:block;margin-top:2px;font-family:var(--mono);font-size:14px;font-weight:600;color:var(--text)}
.oc.call .go{background:rgba(45,212,167,.17);color:var(--up)}
.oc.put .go{background:rgba(244,82,95,.17);color:var(--dn)}
button.oc:disabled .go{background:rgba(137,148,166,.12);color:var(--dim)}
button.oc:disabled .go b{display:none}
/* ---- a report the model cannot price ---- */
.evwarn{display:block;margin-bottom:7px;padding:8px 10px;border-radius:8px;border:1px solid rgba(245,165,36,.4);
  background:rgba(245,165,36,.1);color:#f5c060;font-weight:600;line-height:1.45}
/* ---- percent moves ---- */
.oc .ask em{display:block;font-family:var(--mono);font-style:normal;font-size:11.5px;font-weight:600;letter-spacing:0;margin-top:2px}
.oc .ask em.up{color:var(--up)}
.oc .ask em.dn{color:var(--dn)}
.kv .pp{font-weight:700;margin-left:4px}
.posbar{display:flex;justify-content:space-between;align-items:center;gap:10px;max-width:1300px;margin:8px auto 0;
  padding:7px 11px;border-radius:9px;font-size:13px;border:1px solid var(--line2);background:var(--p2)}
.posbar[hidden]{display:none}
.posbar.up{border-color:rgba(45,212,167,.45);background:rgba(45,212,167,.08)}
.posbar.dn{border-color:rgba(244,82,95,.45);background:rgba(244,82,95,.08)}
.posbar .pw{font-family:var(--mono);font-weight:600;color:var(--text);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.posbar .pv{font-family:var(--mono);white-space:nowrap}
.posbar.up .pv{color:var(--up)}
.posbar.dn .pv{color:var(--dn)}
.posbar .pv b{font-size:14px;margin-right:6px}
/* ---- the account strip ---- */
.acct{display:flex;gap:14px;align-items:center;max-width:1300px;margin:8px auto 0;padding:6px 11px;border-radius:9px;
  font-family:var(--mono);font-size:12px;color:var(--dim);border:1px solid var(--line2);background:var(--p2);min-height:0;
  width:100%;text-align:left;white-space:nowrap;overflow-x:auto;scrollbar-width:none;font-weight:500;cursor:pointer}
.acct::-webkit-scrollbar{display:none}
.acct:hover{border-color:var(--acc)}
.acct b{color:var(--text);font-weight:600}
.acct .tup{color:var(--up)} .acct .tdn{color:var(--dn)}
.acct .warn{color:var(--fib)} .acct .bad{color:var(--dn);font-weight:700}
.acct .off{color:var(--dn);font-weight:700}
.acct .lnk{margin-left:auto;color:var(--acc);font-weight:600}
/* ---- the rules line under the cards ---- */
.rl{margin-top:9px;font-size:11.5px;color:var(--dim);line-height:1.6;font-family:var(--mono)}
.rl b{color:var(--text);font-weight:600}
.rl .bad{color:var(--fib)}
/* ---- the rules pane ---- */
.rf{display:flex;flex-direction:column;gap:4px;font-size:10.5px;color:var(--dim2);text-transform:uppercase;letter-spacing:.9px;font-weight:600}
.rf small{text-transform:none;letter-spacing:0;font-weight:500;color:var(--dim2);font-size:10.5px}
.chk.rc{align-items:flex-start;margin-top:10px}
.chk.rc input{margin-top:2px}
.chk.rc small{display:block;color:var(--dim2);font-size:11px;margin-top:1px}
.rbook{margin-top:14px}
.rbook h5{margin:12px 0 4px;font-size:10.5px;text-transform:uppercase;letter-spacing:1px;color:var(--fib)}
.rbook p{margin:0 0 7px;font-size:12.5px;line-height:1.5}
.rbook p small{display:block;color:var(--dim2);font-size:11.5px}
/* ---- debrief and record overlays ---- */
.ovl{position:fixed;inset:0;z-index:110;background:rgba(3,5,10,.8);overflow-y:auto;-webkit-overflow-scrolling:touch}
.ovl[hidden]{display:none}
.ovl-card{max-width:520px;margin:6vh auto;background:var(--panel);border:1px solid var(--line2);border-radius:12px;padding:16px;box-shadow:0 18px 50px rgba(0,0,0,.6)}
.ovl-card h4{margin:6px 0 4px;font-size:18px;letter-spacing:-.2px}
.ovl-card textarea{width:100%;background:var(--p2);border:1px solid var(--line2);border-radius:8px;color:var(--text);padding:9px 10px;font-family:var(--sans);font-size:14px;resize:vertical}
.dbf-l{display:block;margin-top:12px;font-size:12.5px;color:var(--dim)}
.dbf-l textarea{margin-top:5px}
.stars{display:flex;gap:6px;margin-top:6px}
.stars button{min-height:36px;width:40px;padding:0;font-size:16px}
.stars button.on{border-color:var(--fib);color:var(--fib);background:rgba(245,165,36,.12)}
.rec-in{max-width:980px;margin:0 auto;padding:14px 14px 40px}
.rec-top{display:flex;align-items:center;gap:10px;margin-bottom:12px}
.rec-top h4{margin:4px 0 0;font-size:22px;letter-spacing:-.4px;font-family:var(--mono)}
.rec-top button{margin-left:auto}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:1px;background:var(--line);border:1px solid var(--line);border-radius:11px;overflow:hidden;margin-bottom:14px}
.tile{background:var(--panel);padding:12px 14px;display:flex;flex-direction:column;gap:3px;min-width:0}
.tile span{font-size:9.5px;text-transform:uppercase;letter-spacing:1px;color:var(--dim2)}
.tile b{font-family:var(--mono);font-size:19px;font-weight:600;letter-spacing:-.5px}
.tile i{font-style:normal;font-size:10.5px;color:var(--dim2);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.rsec{background:var(--panel);border:1px solid var(--line);border-radius:11px;padding:13px 14px;margin-bottom:12px}
.rsec h3{margin-bottom:8px}
.rgrid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px}
.rgrid .rsec{margin-bottom:0}
@media(max-width:700px){.rgrid{grid-template-columns:1fr}}
svg.eq{display:block;width:100%;height:auto}
.rchips{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}
.rchips button{min-height:34px;font-size:12px}
.rchips button.on{border-color:var(--acc);color:var(--text);background:rgba(123,108,246,.16)}
.sessrec{display:flex;gap:10px;align-items:baseline;padding:8px 0;border-bottom:1px solid var(--line);font-size:12.5px;flex-wrap:wrap}
.sessrec:last-child{border-bottom:0}
.sessrec .d{font-family:var(--mono);color:var(--dim);min-width:150px}
.sessrec .q{color:var(--dim);font-size:11.5px;flex-basis:100%;line-height:1.45}
.sessrec .q b{color:var(--text)}
.hab{display:flex;align-items:baseline;gap:12px;padding:8px 0;border-bottom:1px solid var(--line)}
.hab:last-child{border-bottom:0}
.hab b{font-family:var(--mono);font-size:15px;min-width:80px;text-align:right}
.hab .h{font-weight:650;font-size:13px}
.hab .w{color:var(--dim2);font-size:11.5px;display:block}
.recta{width:100%;min-height:64px;background:var(--p2);border:1px solid var(--line2);border-radius:8px;color:var(--text);padding:8px;font-family:var(--mono);font-size:11.5px;margin-top:8px}
.gr .b i{color:var(--dim2);font-style:italic}
/* ---- what the day offered ---- */
.lesson{margin-top:12px;font-size:12.5px;line-height:1.55;color:var(--dim)}
.lesson b{color:var(--text)} .lesson b.up{color:var(--up)} .lesson b.dn{color:var(--dn)}
.lesson h5{margin:12px 0 4px;font-size:10.5px;text-transform:uppercase;letter-spacing:1px;color:var(--acc)}
.lesson p{margin:0 0 6px}
.lesson ol{margin:4px 0 6px 18px;padding:0}
.lesson li{margin:4px 0}
@media(min-width:900px){
  .wrap{display:grid;grid-template-columns:1fr 350px;gap:16px;align-items:start}
  .right{position:sticky;top:112px}
  .actions{position:static;background:transparent;backdrop-filter:none;border-top:none;padding:11px 0 0}
  .chartbox{border-radius:10px 10px 0 0;overflow:hidden;border:1px solid var(--line);border-bottom:none}
  .ov{border:1px solid var(--line);border-radius:0 0 10px 10px}
  .rail{border-radius:10px;margin-top:10px;border:1px solid var(--line)}
  footer{grid-column:1/-1}
}
@media(max-width:899px){
  .mp-brand h1{font-size:22px}
  .mp-back{margin-left:0}
  .actions{padding-bottom:calc(env(safe-area-inset-bottom) + 10px)}
  .hint{top:10px}
  /* The day now lives in the picker and the timeframe in the bar below, so the
     four-line clock block that wrapped beside the price comes down to the time. */
  .clkx{display:none}
  .row1{gap:9px}
  .tksel{font-size:17px;padding:3px 26px 3px 10px}
  .px{font-size:18px}
  .chg{font-size:11px;padding:2px 6px;white-space:nowrap}
  .ssel{flex:1 1 auto}
  .ohlc{font-size:12px}
  .acct{gap:10px;font-size:11.5px;padding:6px 9px}
}
/* On a desktop the chart stays pinned while the ticket scrolls beside it. The
   buy cards sit under the size and order settings, below the fold on a laptop,
   and scrolling down to them used to take the chart out of view. Only where the
   window is tall enough to hold the whole chart column. */
@media(min-width:900px) and (min-height:760px){
  .left{position:sticky;top:146px}
  .right{position:static}
}
@media(prefers-reduced-motion:reduce){button:active:not(:disabled){transform:none}}
`;

/**
 * The banner says which kind of data is actually loaded, because the answer
 * changes: with recorded sessions embedded the candles are measured, and only
 * the option quotes are modelled. Claiming "simulated" over real bars would be
 * as wrong as the reverse.
 */
function bannerFor(reportHref: string, sessions: ReplaySession[], vol?: PracticeVol): string {
  const symbols = [...new Set(sessions.map((s) => s.symbol))];
  const dates = sessions.map((s) => s.date).sort();

  const note = sessions.length
    ? `<b>Real candles, modelled options</b>
       Every candle is a measured 1-minute bar from an actual session, with the pre-market and after-hours in 5-minute bars &mdash;
       ${sessions.length} recorded ${sessions.length === 1 ? "day" : "days"} across
       ${symbols.length} ${symbols.length === 1 ? "symbol" : "symbols"}
       (${esc(symbols.slice(0, 8).join(", "))}), ${esc(dates[0])} to ${esc(dates[dates.length - 1])}.
       A random one loads each time.
       <span>Option prices are modelled rather than quoted, but not guessed: the volatility in them is
       the market&rsquo;s own &mdash; that day&rsquo;s VXN or VIX, minute by minute &mdash; scaled to each
       ticker by how its options really traded${vol && vol.calibrations.length ? ` (measured ${esc(vol.calibrations[vol.calibrations.length - 1].date)})` : ""}.
       You buy at the ask and sell at the bid, on realistic spreads.</span>`
    : `<b>Generated prices</b>
       No recorded sessions are embedded yet, so this falls back to a seeded random walk.
       <span>Run the tool once with a network connection to record real sessions; the library
       grows by a day per symbol per run.</span>`;

  return `<header class="mp-head"><div class="mp-wrap">
  <div class="mp-brand">
    <div>
      <h1>Practice</h1>
      <p>Real days replayed bar by bar, traded on your own account under your own rules</p>
    </div>
    <button type="button" class="mp-guide" id="guideOpen">How to use this page</button>
    <a class="mp-back" href="${reportHref}">&larr; Back to the report</a>
  </div>
  <div class="sim ${sessions.length ? "real" : ""}"><div>${note}</div></div>
</div></header>`;
}

const esc = (s: string) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/**
 * Builds the practice page from the vendored app: its body and script are
 * carried over untouched, wrapped in the report's chrome and stylesheet.
 */
/**
 * The same bars in a little under half the bytes, and exactly the same
 * numbers: prices become whole cents measured from the previous close, which
 * is lossless for two-decimal prices, and volume is kept whole. Twelve days
 * of seven tickers would otherwise add about a megabyte to a page opened on
 * a phone.
 */
function compactSession(s: ReplaySession) {
  const z: number[] = [];
  const cents = (n: number) => Math.round(n * 100);
  const base = cents(s.bars[0][0]);
  let pc = base;
  for (const [o, h, l, c, v] of s.bars) {
    const O = cents(o), C = cents(c);
    z.push(O - pc, cents(h) - O, O - cents(l), C - O, Math.round(v));
    pc = C;
  }
  // Extended hours the same way, in sixes: the 5-minute slot, then the open
  // as cents from the previous close (the first one absolute), and the rest.
  const ext = (rows: ExtBar[]) => {
    const out: number[] = [];
    let prev: number | null = null;
    for (const [m, o, h, l, c, v] of rows) {
      const O = cents(o), C = cents(c);
      out.push(m / 5, prev == null ? O : O - prev, cents(h) - O, O - cents(l), C - O, Math.round(v));
      prev = C;
    }
    return out;
  };
  const x = s.ext ? { pre: ext(s.ext.pre), post: ext(s.ext.post) } : undefined;
  return { symbol: s.symbol, date: s.date, carried: s.carried, p: base, z, ...(x ? { x } : {}) };
}

export async function renderPractice(
  vendorPath: string,
  reportHref = "latest.html",
  sessions: ReplaySession[] = [],
  vol?: PracticeVol,
): Promise<string> {
  const src = await readFile(vendorPath, "utf8");

  const bodyOpen = src.search(/<body[^>]*>/i);
  const bodyClose = src.lastIndexOf("</body>");
  if (bodyOpen === -1 || bodyClose === -1) {
    throw new Error(`practice app: no <body> found in ${vendorPath}`);
  }
  const body = src.slice(src.indexOf(">", bodyOpen) + 1, bodyClose);

  // Embedded ahead of the app script, which reads window.MP_SESSIONS on load.
  // JSON.stringify cannot emit "</script>", but a symbol could in principle
  // carry a "<", so the sequence is escaped rather than trusted.
  const data = `<script>window.MP_SESSIONS=${JSON.stringify(sessions.map(compactSession)).replace(/</g, "\\u003c")};</script>`;

  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<meta name="color-scheme" content="dark">
<meta name="theme-color" content="#080b11">
<title>Practice &middot; Market Prep</title>
<style>${SKIN}</style>
</head><body>
${bannerFor(reportHref, sessions, vol)}
${data}
${vol ? `<script>window.MP_VOL=${JSON.stringify(vol.embed)};window.MP_VOLCAL=${JSON.stringify(vol.calibrations).replace(/</g, "\\u003c")};window.MP_EVENTS=${JSON.stringify(vol.events ?? {}).replace(/</g, "\\u003c")};window.MP_RULEBOOK=${JSON.stringify(vol.rulebook ?? null).replace(/</g, "\\u003c")};</script>` : ""}
${body}
</body></html>`;
}
