import { readFile } from "node:fs/promises";
import { FONT_CSS } from "./fonts.ts";
import type { ReplaySession } from "./replay.ts";

/**
 * The practice terminal, re-skinned to match the report.
 *
 * The app's own markup and script are kept verbatim -- every class name in it
 * is load-bearing, since the script builds panes by writing those classes -- so
 * this replaces the stylesheet and wraps the result in the report's chrome
 * rather than rewriting the app.
 *
 * The prices in here are generated by a seeded random walk. That is the whole
 * point of a practice tool, but it sits one click from a report where every
 * number is measured from real bars, so the page says which it is in a place
 * you cannot scroll past.
 */

const SKIN = `
${FONT_CSS}
:root{
  /* The report's tokens, mapped onto the names the app already uses. */
  --bg:#080b11; --panel:#121826; --p2:#0d1220; --line:#1d2637; --line2:#2b3547;
  --text:#e9edf5; --dim:#8994a6; --dim2:#67717f;
  --up:#2dd4a7; --dn:#f4525f; --fib:#f5a524; --acc:#7b6cf6;
  color-scheme:dark;
  --mono:'IBM Plex Mono',ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  --sans:'Archivo',-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
html,body{margin:0;background:var(--bg);color:var(--text);font-family:var(--sans);font-size:14px;overscroll-behavior:none}
button,input,select{font-family:var(--sans);color:var(--text);font-size:13.5px}
button{cursor:pointer;background:var(--p2);border:1px solid var(--line2);border-radius:8px;padding:0 12px;min-height:38px;font-weight:600}
button:active:not(:disabled){transform:scale(.97)}
button:disabled{opacity:.3}
button:focus-visible,select:focus-visible,input:focus-visible{outline:2px solid var(--acc);outline-offset:1px}
input,select{background:var(--p2);border:1px solid var(--line2);border-radius:8px;padding:9px 10px;width:100%;
  font-family:var(--mono);font-size:14px}
.n,.px,.chg,.clk,.ohlc,.seed{font-family:var(--mono);font-variant-numeric:tabular-nums}
.up,.u{color:var(--up)} .dn,.d{color:var(--dn)}

/* ---- masthead ---------------------------------------------------- */
.mp-head{border-bottom:1px solid var(--line);padding:20px 0 0;position:relative;overflow:hidden}
.mp-head::before{content:"";position:absolute;inset:-60% -20% auto -20%;height:220%;
  background:radial-gradient(60% 55% at 18% 40%,rgba(123,108,246,.16),transparent 70%);pointer-events:none}
.mp-wrap{max-width:1300px;margin:0 auto;padding:0 14px;position:relative}
.mp-brand{display:flex;align-items:flex-end;gap:16px;flex-wrap:wrap}
.mp-brand h1{margin:0;font-size:27px;line-height:1;letter-spacing:-1px;font-weight:700}
.mp-brand p{margin:6px 0 0;color:var(--dim);font-size:12.5px}
.mp-back{margin-left:auto;display:inline-flex;align-items:center;gap:7px;text-decoration:none;
  border:1px solid var(--line2);border-radius:8px;padding:9px 14px;color:var(--dim);font-weight:650;font-size:13px}
.mp-back:hover{color:var(--text);border-color:var(--acc);background:rgba(123,108,246,.1)}
.sim{display:flex;align-items:flex-start;gap:10px;margin:16px 0 0;padding:11px 14px;border-radius:9px;
  border:1px solid rgba(245,165,36,.4);background:rgba(245,165,36,.08);color:var(--fib);font-size:12.5px;line-height:1.5}
.sim b{display:block;font-size:11px;text-transform:uppercase;letter-spacing:1.2px;margin-bottom:3px}
.sim.real{border-color:rgba(45,212,167,.38);background:rgba(45,212,167,.07);color:var(--up)}
.sim span{color:var(--dim)}

/* ---- app chrome -------------------------------------------------- */
.top{position:sticky;top:0;z-index:20;background:rgba(8,11,17,.94);backdrop-filter:blur(10px);
  border-bottom:1px solid var(--line);padding:10px 14px 9px}
.row1{display:flex;align-items:center;gap:11px;max-width:1300px;margin:0 auto}
/* The ticker used to be bare text with a faint caret -- it read as a heading,
   so nobody found out it could be changed. It is a bordered control now. */
.tksel{background-color:var(--p2);border:1px solid var(--line2);border-radius:9px;font-family:var(--sans);font-size:19px;
  font-weight:700;letter-spacing:-.3px;padding:3px 28px 3px 11px;min-height:0;width:auto;cursor:pointer;
  -webkit-appearance:none;appearance:none;
  background-image:linear-gradient(45deg,transparent 50%,var(--dim) 50%),linear-gradient(135deg,var(--dim) 50%,transparent 50%);
  background-position:calc(100% - 15px) 50%,calc(100% - 10px) 50%;background-size:5px 5px;background-repeat:no-repeat}
.tksel:hover{border-color:var(--acc)}
.px{font-size:20px;font-weight:600;letter-spacing:-.4px}
.chg{font-size:12px;padding:2px 8px;border-radius:5px;font-weight:600}
.chg.u{color:var(--up);background:rgba(45,212,167,.14)}
.chg.d{color:var(--dn);background:rgba(244,82,95,.14)}
.clk{margin-left:auto;font-size:12px;color:var(--dim);text-align:right;line-height:1.3;white-space:nowrap}
.clk #clk{color:var(--text);font-weight:600;font-size:13px}
.clkx{font-size:10.5px}
.ohlc{font-size:12.5px;color:#a3adbb;margin:8px auto 0;max-width:1300px;height:17px;white-space:nowrap;overflow:hidden}
.ohlc b{color:var(--text);font-weight:600}

/* Restart / new day / which day: in the header, where they can be found. */
.sessrow{display:flex;gap:7px;align-items:center;max-width:1300px;margin:9px auto 0}
.ssel{flex:0 1 240px;min-width:0;width:auto;min-height:34px;padding:0 28px 0 11px;font-family:var(--mono);font-size:12.5px;
  border-radius:8px;background-color:var(--p2);border:1px solid var(--line2);color:var(--text);cursor:pointer;
  -webkit-appearance:none;appearance:none;
  background-image:linear-gradient(45deg,transparent 50%,var(--dim) 50%),linear-gradient(135deg,var(--dim) 50%,transparent 50%);
  background-position:calc(100% - 15px) 50%,calc(100% - 10px) 50%;background-size:5px 5px;background-repeat:no-repeat}
.ssel:disabled{opacity:.5;cursor:default}
.sbtn{flex:0 0 auto;min-height:34px;padding:0 13px;font-size:12.5px;white-space:nowrap}
.sbtn.sprim{background:rgba(123,108,246,.16);border-color:var(--acc);color:var(--text)}

.tfbar{display:flex;gap:5px;overflow-x:auto;padding:9px 14px 8px;scrollbar-width:none;
  border-bottom:1px solid var(--line);background:var(--bg);max-width:1300px;margin:0 auto}
.tfbar::-webkit-scrollbar{display:none}
.tf{flex:0 0 auto;min-height:32px;padding:0 13px;border-radius:8px;font-family:var(--mono);font-size:12.5px;
  background:transparent;border:1px solid var(--line2);color:var(--dim);font-weight:500}
.tf.on{background:rgba(123,108,246,.16);border-color:var(--acc);color:var(--text);font-weight:600}

.chartbox{position:relative;background:#0b1017}
canvas{display:block;width:100%;touch-action:none}
.ov{position:absolute;top:8px;left:10px;display:flex;gap:5px;flex-wrap:wrap;max-width:70%}
.badge{font-family:var(--mono);font-size:10px;padding:3px 8px;border-radius:5px;min-height:0;font-weight:500;
  background:rgba(13,18,32,.85);border:1px solid var(--line2);color:var(--dim)}
.badge.on{color:var(--text);border-color:var(--acc);background:rgba(123,108,246,.14)}
.ctsel{font-family:var(--mono);font-size:10px;padding:3px 19px 3px 8px;width:auto;min-height:0;border-radius:5px;
  background-color:rgba(13,18,32,.9);border:1px solid var(--line2);color:var(--text);
  -webkit-appearance:none;appearance:none;
  background-image:linear-gradient(45deg,transparent 50%,var(--dim) 50%),linear-gradient(135deg,var(--dim) 50%,transparent 50%);
  background-position:calc(100% - 9px) 9px,calc(100% - 5px) 9px;background-size:4px 4px;background-repeat:no-repeat}
.fitbtn{position:absolute;right:60px;bottom:26px;font-family:var(--mono);font-size:10.5px;padding:4px 9px;
  min-height:0;background:rgba(123,108,246,.16);border:1px solid var(--acc);color:var(--acc);display:none}
.fitbtn.show{display:block}

.rail{display:flex;gap:6px;overflow-x:auto;padding:9px 12px;background:var(--panel);
  border-top:1px solid var(--line);border-bottom:1px solid var(--line);scrollbar-width:none}
.rail::-webkit-scrollbar{display:none}
.tool{flex:0 0 auto;width:42px;height:38px;display:grid;place-items:center;padding:0;background:transparent;border:1px solid var(--line2)}
.tool.on{background:rgba(123,108,246,.18);border-color:var(--acc)}
.tool.on svg{stroke:var(--acc)}
.tool svg{width:18px;height:18px;fill:none;stroke:var(--dim);stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}
.rail .lbl{flex:0 0 auto;align-self:center;font-size:10px;color:var(--dim2);text-transform:uppercase;letter-spacing:1.1px;font-weight:600;padding-right:2px}

/* Two rows, each with its own track sizes. One grid cannot do this: the side
   buttons would inherit the transport columns and come out uneven -- which is
   how Buy put ended up half the width of Buy call. */
.actions{position:sticky;bottom:0;z-index:18;display:flex;flex-direction:column;gap:7px;
  padding:10px 12px;background:rgba(8,11,17,.96);backdrop-filter:blur(10px);border-top:1px solid var(--line)}
.trow{display:grid;grid-template-columns:46px 1fr 46px 76px;gap:7px}
.srow{display:grid;grid-template-columns:1fr 1fr;gap:7px}
.actions button{min-height:46px;font-weight:650;font-size:13.5px;padding:0 4px;white-space:nowrap}
.actions select{min-height:46px;padding:0 4px;font-size:12.5px;text-align:center}
.actions #back,.actions #auto{font-size:15px;padding:0}
.bnext{background:var(--acc);border-color:var(--acc);color:#fff}
.blong{border-color:rgba(45,212,167,.55);color:var(--up);background:rgba(45,212,167,.1)}
.bshort{border-color:rgba(244,82,95,.5);color:var(--dn);background:rgba(244,82,95,.1)}

/* ---- panes ------------------------------------------------------- */
.tabs{display:flex;gap:4px;overflow-x:auto;padding:12px 0 0;scrollbar-width:none}
.tabs::-webkit-scrollbar{display:none}
.tab{flex:0 0 auto;min-height:34px;padding:0 13px;font-size:12.5px;background:transparent;border:1px solid transparent;
  color:var(--dim);border-radius:8px 8px 0 0;font-weight:600}
.tab.on{background:var(--panel);border-color:var(--line);border-bottom-color:var(--panel);color:var(--text)}
.pane{background:var(--panel);border:1px solid var(--line);border-radius:0 10px 10px 10px;margin:0 0 14px;padding:14px;min-height:190px}
h3{font-size:10.5px;color:var(--dim2);font-weight:650;margin:0 0 10px;text-transform:uppercase;letter-spacing:1.2px}
h3.sp{margin-top:18px}
.empty{color:var(--dim);font-size:13px;line-height:1.55}

.seg{display:flex;border:1px solid var(--line2);border-radius:9px;overflow:hidden;margin-bottom:12px}
.seg button{flex:1;border:none;border-radius:0;background:transparent;min-height:40px;color:var(--dim)}
.seg button.on{background:rgba(123,108,246,.2);color:var(--text);font-weight:700;box-shadow:inset 0 -2px 0 var(--acc)}
.chips{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}
.chips button{min-height:34px;font-size:11.5px;font-family:var(--mono);padding:0 10px;font-weight:500}
.chips button.on{border-color:var(--acc);color:var(--text);background:rgba(123,108,246,.14)}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:9px}
.grid2 label{font-size:10.5px;color:var(--dim2);text-transform:uppercase;letter-spacing:.9px;font-weight:600}
.grid2 label span{display:block;margin-bottom:5px}
.quote{background:var(--p2);border:1px solid var(--line2);border-radius:9px;padding:11px;margin-top:11px}
.quote .big{font-family:var(--mono);font-size:18px;font-weight:600;letter-spacing:-.3px}
.greeks{display:flex;gap:12px;flex-wrap:wrap;font-family:var(--mono);font-size:11px;color:var(--dim);margin-top:8px}
.greeks b{color:var(--text);font-weight:600}
.kv{display:flex;justify-content:space-between;font-family:var(--mono);font-size:13px;padding:6px 0;border-bottom:1px solid var(--line)}
.kv:last-child{border-bottom:none}
.kv .k{color:var(--dim)}
.mgmt{display:grid;grid-template-columns:1fr 1fr 1fr;gap:7px;margin-top:11px}
.mgmt button{min-height:40px;font-size:12.5px}
.fibrow{display:flex;justify-content:space-between;font-family:var(--mono);font-size:12.5px;padding:7px 9px;border-radius:6px}
.fibrow+.fibrow{margin-top:1px}
.fibrow .k{color:var(--dim)}
.fibrow.ext .k{color:var(--fib)}
.fibrow.edge{background:rgba(123,108,246,.12)}
.fibrow.edge .k{color:var(--acc)}
.fibrow.near{outline:1px solid var(--line2)}
.fibrow small{color:var(--dim2);font-size:10.5px;margin-left:5px}
.tape div{font-family:var(--mono);font-size:12px;color:var(--dim);padding:3px 0;line-height:1.45}
.tape .hl{color:var(--text)} .tape .g{color:var(--up)} .tape .r{color:var(--dn)} .tape .y{color:var(--fib)}
.scroll{max-height:270px;overflow-y:auto;-webkit-overflow-scrolling:touch}
.scroll::-webkit-scrollbar{width:8px} .scroll::-webkit-scrollbar-thumb{background:var(--line2);border-radius:4px}
table{width:100%;border-collapse:collapse;font-family:var(--mono);font-size:11.5px}
th{text-align:left;color:var(--dim2);font-weight:650;padding:6px 4px;border-bottom:1px solid var(--line2);
  text-transform:uppercase;letter-spacing:.7px;font-size:9.5px}
td{padding:7px 4px;border-bottom:1px solid var(--line)}
tr.atm td{background:rgba(123,108,246,.1)}
tr.pick td{outline:1px solid var(--acc)}
.chain td{cursor:pointer}
.stats{display:flex;gap:14px;flex-wrap:wrap;font-family:var(--mono);font-size:13px;margin-bottom:12px}
.stats span{color:var(--dim)}
.gr{display:flex;gap:9px;padding:10px 0;border-bottom:1px solid var(--line)}
.gr:last-child{border-bottom:none}
.gr .m{font-family:var(--mono);font-size:13.5px;line-height:1.3}
.gr .m.ok{color:var(--up)} .gr .m.bad{color:var(--dn)} .gr .m.mid{color:var(--fib)} .gr .m.h{color:var(--acc)}
.gr .b{font-size:13px;line-height:1.55}
.setup{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:12px}
.setup select{width:auto;flex:1;min-width:130px}
.seed{font-size:12px;color:var(--acc);background:var(--p2);border:1px solid var(--line2);border-radius:7px;padding:9px 11px}
footer{color:var(--dim2);font-size:11px;text-align:center;padding:0 20px 28px;line-height:1.6;max-width:640px;margin:0 auto}

.wrap{max-width:1300px;margin:0 auto;padding:0 14px 20px}
.left{min-width:0}
@media(min-width:900px){
  .wrap{display:grid;grid-template-columns:1fr 350px;gap:16px;align-items:start}
  .right{position:sticky;top:112px}
  .actions{position:static;background:transparent;backdrop-filter:none;border-top:none;padding:11px 0 0}
  .chartbox{border-radius:10px;overflow:hidden;border:1px solid var(--line)}
  .rail{border-radius:10px;margin-top:10px;border:1px solid var(--line)}
  footer{grid-column:1/-1}
}
@media(max-width:899px){
  .mp-brand h1{font-size:22px}
  .mp-back{margin-left:0}
  .actions{padding-bottom:calc(env(safe-area-inset-bottom) + 10px)}
  /* Ten indicator chips and a chart-type picker cannot float over a phone-width
     chart: they wrap to three rows and bury the candles. Below 900px they get
     their own scrolling strip under the chart instead. */
  .ov{position:static;max-width:none;flex-wrap:nowrap;overflow-x:auto;gap:6px;
    padding:8px 12px;background:var(--panel);border-top:1px solid var(--line);
    scrollbar-width:none;-webkit-overflow-scrolling:touch}
  .ov::-webkit-scrollbar{display:none}
  .badge{flex:0 0 auto;min-height:30px;font-size:11px;padding:0 11px;display:grid;place-items:center}
  .ctsel{flex:0 0 auto;min-height:30px;font-size:11px;padding:0 20px 0 9px;
    background-position:calc(100% - 9px) 13px,calc(100% - 5px) 13px}
  /* nothing covers the top-left now, so auto fit leaves the volume bars alone */
  .fitbtn{right:auto;left:10px;top:10px;bottom:auto}
  /* The day now lives in the picker and the timeframe in the bar below, so the
     four-line clock block that wrapped beside the price comes down to the time. */
  .clkx{display:none}
  .row1{gap:9px}
  .tksel{font-size:17px;padding:3px 26px 3px 10px}
  .px{font-size:18px}
  .chg{font-size:11px;padding:2px 6px;white-space:nowrap}
  .ssel{flex:1 1 auto}
  .ohlc{font-size:12px}
}
@media(prefers-reduced-motion:reduce){button:active:not(:disabled){transform:none}}
`;

/**
 * The banner says which kind of data is actually loaded, because the answer
 * changes: with recorded sessions embedded the candles are measured, and only
 * the option quotes are modelled. Claiming "simulated" over real bars would be
 * as wrong as the reverse.
 */
function bannerFor(reportHref: string, sessions: ReplaySession[]): string {
  const symbols = [...new Set(sessions.map((s) => s.symbol))];
  const dates = sessions.map((s) => s.date).sort();

  const note = sessions.length
    ? `<b>Real candles, modelled options</b>
       Every candle is a measured 1-minute bar from an actual session &mdash;
       ${sessions.length} recorded ${sessions.length === 1 ? "day" : "days"} across
       ${symbols.length} ${symbols.length === 1 ? "symbol" : "symbols"}
       (${esc(symbols.slice(0, 8).join(", "))}), ${esc(dates[0])} to ${esc(dates[dates.length - 1])}.
       A random one loads each time.
       <span>Option prices are still modelled with Black-Scholes rather than quoted, and fills are
       assumed at the mid, so treat the option side as an approximation of the real chain.</span>`
    : `<b>Generated prices</b>
       No recorded sessions are embedded yet, so this falls back to a seeded random walk.
       <span>Run the tool once with a network connection to record real sessions; the library
       grows by a day per symbol per run.</span>`;

  return `<header class="mp-head"><div class="mp-wrap">
  <div class="mp-brand">
    <div>
      <h1>Practice</h1>
      <p>Bar-by-bar replay for rehearsing entries, stops and exits</p>
    </div>
    <a class="mp-back" href="${reportHref}">&larr; Back to the report</a>
  </div>
  <div class="sim ${sessions.length ? "real" : ""}"><div>${note}</div></div>
</div></header>`;
}

const esc = (s: string) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/**
 * Builds the practice page from the vendored app: its body and script are
 * carried over untouched, wrapped in the report's chrome and stylesheet.
 */
export async function renderPractice(
  vendorPath: string,
  reportHref = "latest.html",
  sessions: ReplaySession[] = [],
): Promise<string> {
  const src = await readFile(vendorPath, "utf8");

  const bodyOpen = src.search(/<body[^>]*>/i);
  const bodyClose = src.lastIndexOf("</body>");
  if (bodyOpen === -1 || bodyClose === -1) {
    throw new Error(`practice app: no <body> found in ${vendorPath}`);
  }
  const body = src.slice(src.indexOf(">", bodyOpen) + 1, bodyClose);

  // Embedded ahead of the app script, which reads window.MP_SESSIONS on load.
  // JSON.stringify cannot emit "</script>", but a symbol could in principle
  // carry a "<", so the sequence is escaped rather than trusted.
  const data = `<script>window.MP_SESSIONS=${JSON.stringify(sessions).replace(/</g, "\\u003c")};</script>`;

  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<meta name="color-scheme" content="dark">
<meta name="theme-color" content="#080b11">
<title>Practice &middot; Market Prep</title>
<style>${SKIN}</style>
</head><body>
${bannerFor(reportHref, sessions)}
${data}
${body}
</body></html>`;
}
